# The docker-compose file must begin with the version tag.
# We use "3" since this is the latest version at the time of writing this code.
version: '3.1'

# Please note that docker-composes works with services.
# 1 service = 1 container.
# A service can be a client, server, database server ...
# The section in which services will be described begins with 'services'.
services:
  spring:
    image: mokhovav/just_a_game
    restart: always
    container_name: just_a_game_project
    ports:
       - 80:8080